name: Run Python Crawler Every 3 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"   # 每 5 分鐘（UTC 時區）
  workflow_dispatch:        # 手動觸發（可選）

permissions:
  contents: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run crawler
      run: python evacuate_tw.py

    - name: Commit and push result
      env:
        GITHUB_TOKEN: ${{ secrets.USA_STEP_SECRET}}
      run: |
        git config --global user.name "godknowspe@gmail.com"
        git config --global user.email "godknowspe@gmail.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/godknowspe/STEP_TW.git
        git checkout main
        git add . -u
        git commit -m "Update result"
        git push --force origin main
