name: Run Python Crawler Every 3 Minutes

on:
  schedule:
    - cron: "*/3 * * * *"   # 每 3 分鐘（UTC 時區）
  workflow_dispatch:        # 手動觸發（可選）

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run crawler
      run: python evacuate_tw.py

    - name: Commit and push result
      run: |
        git config --global user.name "godknowspe@gmail.com"
        git config --global user.email "godknowspe@gmail.com"
        git add last_level.json
        git commit -m "Update result"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.USA_STEP_SECRET}}
